#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Writes a manifest holding only the runtime requirements.
 *
 * `composer update --no-dev` does not do what it looks like it does. The
 * development requirements are still *resolved* — they are merely not installed —
 * so a test framework that needs a newer PHP than the library does blocks the
 * install on the library's own minimum version:
 *
 * ```text
 * pestphp/pest[...] require php ^8.4 -> your php version (8.2) does not satisfy that requirement.
 * Running update with --no-dev does not mean require-dev is ignored, it just means
 * the packages will not be installed.
 * ```
 *
 * The minimum-version job has to install what a consumer installs, so this takes
 * the test framework out of the manifest and the job resolves the rest of it:
 *
 * ```sh
 * php tools/resolve-runtime.php
 * COMPOSER=composer.runtime.json composer update
 * ```
 *
 * Resolved fresh rather than installed from the lock, which is the point: a
 * runtime dependency that drops support for the minimum version is what this is
 * here to notice.
 */

$root = dirname(__DIR__);
$source = $root . '/composer.json';

// An argument says where to write it, so a caller can have the manifest and the
// vendor directory it produces in one place of its own choosing.
$target = $argv[1] ?? $root . '/composer.runtime.json';

$manifest = json_decode((string) file_get_contents($source), true, flags: JSON_THROW_ON_ERROR);

// Everything a consumer installs, and nothing else; `autoload` stays so that the
// vendor directory this produces is the one the scripts find. The `require` block
// is copied verbatim rather than listed from what `src/` happens to call, so the
// two extensions a dependency already makes are in it as well:
//
//   ext-mbstring  `src/Reverse/DocumentReader.php` calls `mb_strtolower()`, and
//                 the polyfill that would cover for it, symfony/polyfill-mbstring,
//                 is a development dependency a consumer does not have.
//
//   ext-gd        never called by `src/`, but phpoffice/phpword is this library's
//                 document writer and `PhpWord\Element\Image` calls into it.
//                 Composer checks a transitive requirement at install time, so
//                 this says it on this package rather than on whichever one
//                 happens to make it today.
$runtime = [
    'name' => $manifest['name'] . '-runtime',
    'description' => 'Runtime requirements only, generated by tools/resolve-runtime.php.',
    'type' => $manifest['type'] ?? 'library',
    'license' => $manifest['license'] ?? 'MIT',
    'require' => $manifest['require'],
    'autoload' => $manifest['autoload'],
    'config' => [
        // A manifest resolved from scratch must not run code: only a development
        // dependency would have wanted a plugin, and there are none.
        'allow-plugins' => false,
        'sort-packages' => true,
    ],
];

file_put_contents(
    $target,
    json_encode($runtime, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n",
);

$requirements = count($manifest['require']);
fwrite(
    STDOUT,
    sprintf(
        "%s: %d runtime requirement%s, no development requirements.\n",
        basename($target),
        $requirements,
        $requirements === 1 ? '' : 's',
    ),
);
