#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Writes a manifest holding only the runtime requirements.
 *
 * `composer update --no-dev` does not do what it looks like it does. The
 * development requirements are still *resolved* — they are merely not installed —
 * so a test framework that needs a newer PHP than the library does blocks the
 * install on the library's minimum version:
 *
 * ```text
 * Root composer.json requires pestphp/pest ^5.0 -> satisfiable by pestphp/pest[v5.0.0, ..., v5.2.1].
 * pestphp/pest[...] require php ^8.4 -> your php version (8.2) does not satisfy that requirement.
 * Running update with --no-dev does not mean require-dev is ignored, it just means
 * the packages will not be installed.
 * ```
 *
 * The point of the minimum-version job is to check the library where the library
 * says it works, so it has to install only what a consumer installs. This writes a
 * manifest with the test framework out of it, and the job resolves that:
 *
 * ```sh
 * php tools/resolve-runtime.php
 * COMPOSER=composer.runtime.json composer update --prefer-dist --no-progress
 * ```
 *
 * The dependencies are still resolved fresh, which is the point: if a runtime
 * dependency ever drops support for the minimum version, this is what notices.
 *
 * @see \MarkdownWord\Console\Application
 */

$root = dirname(__DIR__);
$source = $root . '/composer.json';

// An argument says where to write it, so a caller assembling a directory of its
// own can put the manifest straight where it wants the vendor directory to end
// up beside it, rather than resolving over somebody else's.
$target = $argv[1] ?? $root . '/composer.runtime.json';

$manifest = json_decode((string) file_get_contents($source), true, flags: JSON_THROW_ON_ERROR);

// Everything a consumer installs, and nothing else. `autoload` stays so that the
// vendor directory this produces is the same one the scripts find.
$runtime = [
    'name' => $manifest['name'] . '-runtime',
    'description' => 'Runtime requirements only, generated by tools/resolve-runtime.php.',
    'type' => $manifest['type'] ?? 'library',
    'license' => $manifest['license'] ?? 'MIT',
    'require' => $manifest['require'],
    'autoload' => $manifest['autoload'],
    'config' => [
        // No plugins are allowed: a development dependency is the only thing
        // that could need one, and by this point there are none.
        'allow-plugins' => false,
        'sort-packages' => true,
    ],
];

file_put_contents(
    $target,
    json_encode($runtime, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n",
);

$requirements = count($manifest['require']);
fwrite(
    STDOUT,
    sprintf(
        "%s: %d runtime requirement%s, no development requirements.\n",
        basename($target),
        $requirements,
        $requirements === 1 ? '' : 's',
    ),
);
